version: "3.3"

services:
  postgres:
    image: postgres:13.2
    container_name: simple_advert_db
    restart: always
    command: -p 6100
    ports:
      - "6100:6100"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  local_postgres_data:
