"""Create Complaint model

Revision ID: 07de5f4d8fca
Revises: 2671f329c961
Create Date: 2023-07-06 06:52:54.753492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07de5f4d8fca'
down_revision = '2671f329c961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advert_id'], ['advert.id'], name='fk_advert_feedback_id_feedback'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_advert_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
