"""Create Feedback model

Revision ID: 2671f329c961
Revises: 74e4362de7d2
Create Date: 2023-07-05 05:44:24.589331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2671f329c961'
down_revision = '74e4362de7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advert_id'], ['advert.id'], name='fk_advert_feedback_id_feedback'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_advert_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
